name: Build and Release for Windows

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger on version tags
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Get version from tag or use default
        id: get_version
        shell: pwsh
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          if (-not $version) {
            $version = "1.0.1-snapshot"
          }
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "Detected version: $version"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Package the application
        run: ./gradlew packageReleaseMsi

      - name: List MSI directory
        run: |
          dir "build\compose\binaries\main\msi"

      - name: Find MSI file
        id: find_msi
        shell: pwsh
        run: |
          $msiFile = Get-ChildItem -Path "build\compose\binaries\main\msi" -Filter "*.msi" | Select-Object -First 1
          if ($msiFile) {
            echo "MSI_PATH=$($msiFile.FullName)" >> $env:GITHUB_OUTPUT
            echo "MSI_NAME=$($msiFile.Name)" >> $env:GITHUB_OUTPUT
            echo "Found MSI: $($msiFile.FullName)"
          } else {
            echo "No MSI file found"
            exit 1
          }

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: |
            ${{ steps.find_msi.outputs.MSI_PATH }}
          if-no-files-found: error

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_msi.outputs.MSI_PATH }}
          asset_name: Merchant-Center-${{ steps.get_version.outputs.VERSION }}.msi
          asset_content_type: application/octet-stream

      - name: Upload to Release (Fallback)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_msi.outputs.MSI_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
