name: Build and Release for Windows

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger on version tags
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Get version from tag
        id: get_version
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Package the application
        run: ./gradlew packageMsi

      - name: List build directory
        run: |
          dir build\*

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: |
            build/**/*.exe
            build/**/*.msi
            build/**/*-*.exe
            build/**/*-*.msi
            build/**/**/*-*.msi
          if-no-files-found: warn

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build\compose\binaries\main\msi\Merchant Center-1.0.0.msi
          asset_name: Merchant-Center-${{ steps.get_version.outputs.VERSION }}.msi
          asset_content_type: application/octet-stream

      - name: Upload to Release using softprops
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build\compose\binaries\main\msi\Merchant Center-1.0.0.msi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
