name: Build for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created  # This will trigger actions when a release is created

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Specify the JDK version you need
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build  # Run the Gradle build command

      - name: Run tests
        run: ./gradlew test  # Run your tests

      - name: Package the application
        run: ./gradlew packageMsi  # Package your application

      - name: List build directory
        run: |
          dir build\*  # List files in the build directory

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: windows-build-artifacts
          path: |
            build/**/*.exe
            build/**/*.msi
            build/**/*-*.exe
            build/**/*-*.msi
            build/**/**/*-*.exe
            build/**/**/*-*.msi
          if-no-files-found: warn
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}  # Tag name (e.g., refs/tags/v1.0.0)
          release_name: 'Release ${{ github.ref }}'  # Use GitHub ref as release name
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}  # The tag name to attach the assets to
          files: |
            build/**/*.exe
            build/**/*.msi
            build/**/*-*.exe
            build/**/*-*.msi
            build/**/**/*-*.exe
            build/**/**/*-*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
